######################################################################
# Automatically generated by qmake (2.01a) mié oct 17 11:48:49 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += sobel2.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
